// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9uf5UotG7FF4V9E3HHSVhr-WiCnWTntg',
    appId: '1:673309951497:web:34043c8cdf120e571f5ad8',
    messagingSenderId: '673309951497',
    projectId: 'retailer-e7bb3',
    authDomain: 'retailer-e7bb3.firebaseapp.com',
    storageBucket: 'retailer-e7bb3.firebasestorage.app',
    measurementId: 'G-VYMKRQPN1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxYO7BE8UhMwPQo5a1g4oZqFjYh21GyeM',
    appId: '1:673309951497:android:91d0e01dd9e22f2a1f5ad8',
    messagingSenderId: '673309951497',
    projectId: 'retailer-e7bb3',
    storageBucket: 'retailer-e7bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8YhhAit8eiys9_6pqNESpekVZFiWg-p0',
    appId: '1:673309951497:ios:c6b63e8f9b3099411f5ad8',
    messagingSenderId: '673309951497',
    projectId: 'retailer-e7bb3',
    storageBucket: 'retailer-e7bb3.firebasestorage.app',
    androidClientId: '673309951497-m869tlj3ia2kfrja3euenumvoi391l4n.apps.googleusercontent.com',
    iosClientId: '673309951497-atsia662l27usr59qomoocdnc2cisc55.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.sixammartUserApp.RunnerTests',
  );
}
